# Generated by Django 3.2.22 on 2023-10-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('naming_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_and_time', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
            options={
                'ordering': ['-naming_id'],
            },
        ),
    ]
