# Generated by Django 3.2.22 on 2023-10-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='duration',
        ),
    ]
