# Generated by Django 3.2.22 on 2023-10-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0012_alter_reservation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['name']},
        ),
    ]
