# Generated by Django 3.2.22 on 2023-10-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0015_remove_reservation_num_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['naming_id']},
        ),
    ]
