# Generated by Django 3.2.22 on 2023-10-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0016_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_guests',
            field=models.PositiveSmallIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
