# Generated by Django 3.2.22 on 2023-10-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0017_reservation_num_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_guests',
            new_name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='0', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requirments',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='naming_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
