# Generated by Django 3.2.22 on 2023-10-27 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0019_auto_20231025_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='special_request',
            new_name='special_request_requirments',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='special_requirments',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='12:00'),
        ),
    ]
