# Generated by Django 3.2.22 on 2024-04-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0021_auto_20240408_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='10:00'),
        ),
    ]
